on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [oldstable, stable]
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v4
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.63
    - name: Test
      run: go test ./...
